basePath: /api/
definitions:
  store.Assignment:
    properties:
      participant_id:
        type: integer
      project_id:
        type: integer
    type: object
  store.AssignmentDetail:
    properties:
      participant_id:
        type: integer
      participant_last_name:
        type: string
      participant_name:
        type: string
      project_id:
        type: integer
      project_name:
        type: string
    type: object
  store.Participants:
    properties:
      email:
        type: string
      firs_name:
        type: string
      identificacion:
        type: string
      last_name:
        type: string
      phone:
        type: string
    type: object
  store.Project:
    properties:
      description:
        type: string
      end_date:
        example: "2024-10-10T00:00:00Z"
        type: string
      name:
        type: string
      project_id:
        type: integer
      start_date:
        example: "2024-10-10T00:00:00Z"
        type: string
      value:
        type: number
    type: object
info:
  contact: {}
  description: Rest Api for test
  title: Rest api
  version: "1.0"
paths:
  /assignments:
    get:
      description: Obtiene la lista de asignaciones con detalles del proyecto y participante
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/store.AssignmentDetail'
            type: array
      summary: Listar asignaciones de proyectos
      tags:
      - AsignarProyecto
    post:
      consumes:
      - application/json
      description: Asigna un proyecto a un estudiante
      parameters:
      - description: Id para asignar un proyecto
        in: body
        name: assignment
        required: true
        schema:
          $ref: '#/definitions/store.Assignment'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/store.Assignment'
      summary: Asignar Proyecto
      tags:
      - AsignarProyecto
  /participant/create:
    post:
      consumes:
      - application/json
      description: Crea un nuevo participante
      parameters:
      - description: Datos del participante
        in: body
        name: participant
        required: true
        schema:
          $ref: '#/definitions/store.Participants'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/store.Participants'
      summary: Crear participante
      tags:
      - Participantes
  /participant/get_alls:
    get:
      description: Retorna la lista de todos los participantes registrados
      produces:
      - application/json
      responses:
        "200":
          description: Lista de participantes
          schema:
            items:
              $ref: '#/definitions/store.Participants'
            type: array
      summary: Obtener todos los participantes
      tags:
      - Participantes
  /project/create:
    post:
      consumes:
      - application/json
      description: Crea un nuevo proyecto
      parameters:
      - description: Datos del participante
        in: body
        name: proyect
        required: true
        schema:
          $ref: '#/definitions/store.Project'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/store.Project'
      summary: Crear proyecto
      tags:
      - Proyectos
  /project/get_alls:
    get:
      description: Retorna la lista de todos los proyectos registrados
      produces:
      - application/json
      responses:
        "200":
          description: Lista de proyectos
          schema:
            items:
              $ref: '#/definitions/store.Project'
            type: array
      summary: Obtener todos los proyectos
      tags:
      - Proyectos
  /project/search:
    get:
      description: Retorna una lista de proyectos cuyo nombre coincide parcialmente
        con el valor buscado
      parameters:
      - description: Nombre del proyecto a buscar
        in: query
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Lista de proyectos encontrados
          schema:
            items:
              $ref: '#/definitions/store.Project'
            type: array
      summary: Buscar proyectos por nombre
      tags:
      - Proyectos
swagger: "2.0"
